name: 'Test actions'

on:
    workflow_dispatch:

jobs:
    test-outputs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Test without ID
              run: |
                echo 'TEST_WITHOUT_ID="WITHOUT_ID"' >> $GITHUB_OUTPUT
            - name: Test with ID
              id: with-id
              run: |
                echo "steps.with-id.outputs.TEST_WITHOUT_ID: ${{ steps.with-id.outputs.TEST_WITHOUT_ID }}"
                echo 'TEST_WITH_ID="WITH_ID"' >> $GITHUB_OUTPUT
            - name: Echo
              run: |
                echo "steps.with-id.outputs.TEST_WITHOUT_ID: ${{ steps.without-id.outputs.TEST_WITHOUT_ID }}"
                echo "steps.with-id.outputs.TEST_WITH_ID: ${{ steps.with-id.outputs.TEST_WITH_ID }}"
            - name: Set 0 variable with ID
              run: |
                echo 'ZERO_ID="1"' >> $GITHUB_OUTPUT
            - name: Does TEST_WITHOUT_ID match '0'
              if: steps.with-id.outputs.ZERO_ID == '0'
              run: |
                echo "steps.with-id.outputs.ZERO_ID == '0' is true"